services:
  webapi:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  postgresdb:
    image: postgres:15-alpine
    container_name: ecommerce_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ozanyaman
      - POSTGRES_PASSWORD=ozan923923
      - POSTGRES_DB=NewDatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: